### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by pgreze** [pgreze/kowners#1]
- [x] Initial Setup
- [x] Upload GraalVM image to Github during PR
- [ ] Add integration tests with git ls-files (current one is with recursive list)
- [ ] Build and push to Github releases jar+GraalVM binaries with https://github.com/actions/upload-release-asset#example-workflow---upload-a-release-asset

**Comment by pgreze** [comment]
[GraalVM Gradle](https://github.com/palantir/gradle-graal) (they're not using [new releases](https://github.com/graalvm/graalvm-ce-builds/releases) by default):

```
🍏 ➜  gw cli:nativeImage

> Task :cli:nativeImage
Build on Server(pid: 5699, port: 63970)
[kowners:5699]    classlist:     536.98 ms
[kowners:5699]        (cap):   3,553.83 ms
[kowners:5699]        setup:   3,957.01 ms
[kowners:5699]   (typeflow):   3,555.78 ms
[kowners:5699]    (objects):   3,218.45 ms
[kowners:5699]   (features):     151.14 ms
[kowners:5699]     analysis:   7,028.08 ms
[kowners:5699]     (clinit):      98.73 ms
[kowners:5699]     universe:     210.73 ms
Warning: Reflection method java.lang.Class.newInstance invoked at kotlin.internal.PlatformImplementationsKt.<clinit>(PlatformImplementations.kt:50)
Warning: Reflection method java.lang.Class.newInstance invoked at kotlin.internal.PlatformImplementationsKt.<clinit>(PlatformImplementations.kt:41)
Warning: Reflection method java.lang.Class.getMethods invoked at kotlin.internal.PlatformImplementations$ReflectAddSuppressedMethod.<clinit>(PlatformImplementations.kt:18)
Warning: Aborting stand-alone image build due to reflection use without configuration.
Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Build on Server(pid: 5699, port: 63970)
[kowners:5699]    classlist:      89.58 ms
[kowners:5699]        (cap):   2,611.17 ms
[kowners:5699]        setup:   2,837.82 ms
[kowners:5699]   (typeflow):   1,339.39 ms
[kowners:5699]    (objects):   1,486.96 ms
[kowners:5699]   (features):     102.55 ms
[kowners:5699]     analysis:   2,982.65 ms
[kowners:5699]     (clinit):      65.71 ms
[kowners:5699]     universe:     156.91 ms
[kowners:5699]      (parse):     213.96 ms
[kowners:5699]     (inline):     647.39 ms
[kowners:5699]    (compile):   1,647.42 ms
[kowners:5699]      compile:   2,696.35 ms
[kowners:5699]        image:     220.43 ms
[kowners:5699]        write:     171.18 ms
[kowners:5699]      [total]:   9,195.55 ms
Warning: Image 'kowners' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation).
native image available at build/graal/kowners (3 MB)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 24s
7 actionable tasks: 4 executed, 3 up-to-date
```

Seems not good regarding [this post](https://e.printstacktrace.blog/graalvm-and-groovy-how-to-start/).
